### PR TITLE
Fix/rr366

### LINKED ISSUE #306: Edit broken
Edit is giving us errors. Here's what happens.

The EditForm does an ajax PATCH request to rebate_forms/:id, and an error happens. 

In the controller there is this rescue:

```
    rescue RebateFormsService::Error
      redirect_to edit_admin_rebate_form_path(@rebate_form), notice: 'The rebate form did not update, please try again.'
```

That means the AJAX request doesn't get an HTTP resposne that looks like an error, instead, it gets an HTTP 302, so the ajax library dutifully also does an HTTP PATCH to the edit path `admin/rebate_forms/:id/edit`, which isn't routed, so then it gets a 404 and nothing more happens.

I commented out that `rescue` so that actual errors are returned to to the browser when the update fails - then @JacOng17 and I chased it the bug to find what the errors are

In the RebateFormService, there's an `update!` function. 

```ruby
  def update!
    council = find_council!
    property = create_or_update_property!(council)
    rebate_form = create_or_update_rebate_form!(property)
    create_or_update_rates_bill!(property)
    rebate_form.calc_rebate_amount!
    raise Error if rebate_form.rebate.blank?
    rebate_form
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotFound
    raise Error
  end
```

it gets as far as `create_or_update_rates_bill!(property)`, which throws an active record error because you can't have a rates_bill with blank rates (the column is `total_rates`)
`ActiveRecord::RecordInvalid (Validation failed: Total rates can't be blank)`

I suggest not catching these errors, as they stop the javascript libraries knowing what's wrong. Instead let the RecordInvalid be returned by the API and then have the javascript in the `EditRebateForm` component's `onSubmit()` learn that the update failed, and the reason it failed is that you can't have a rates rebate for someone with no rates.

### PR DESCRIPTION
**Pull request by mischa-s**
# What has changed and why?
Other income for partner only counts if has partner value is "yes"
# How to test this change

- [x] has tests
- [ ] at least one a reviewer ran the code

closes #306

### CODE REVIEW

File: spec/features/admin/rebate_forms/edit_spec.rb [hunk 1]
```diff
@@ -16,15 +16,14 @@
 
   shared_examples 'can edit' do
     describe '#edit' do
-      xit 'can modify the rebate_form' do
+      it 'can modify the rebate_form' do
         visit "/admin/rebate_forms/#{rebate_form.id}/edit"
         expect(page).to have_text('Name')
-        fill_in 'fields.full_name', with: 'New name'
+        fill_in('fields.full_name', with: 'arnold', fill_options: { clear: :backspace })
```
Comment (CaraHill) [inline spec/features/admin/rebate_forms/edit_spec.rb]: ✨
